"""
brand_config.py  —  Complete multi-industry brand database
60+ brands across Grocery, Retail, Fashion, Finance, Healthcare,
Pharmacy, Tech, Food & Beverage, Automotive, Travel, and more.
"""

BRANDS = {
    "Tesco": {"primary":"#00539F","secondary":"#BFE0F5","accent":"#E31837","text_dark":"#002858","text_light":"#FFFFFF","bg_default":"#BFE0F5","font_family":"Poppins (Modern)","logo_text":"TESCO","logo_shape":"pill","badge_style":"clubcard","category":"UK Grocery","compliance":"tesco","tagline":"Every little helps"},
    "Sainsbury's": {"primary":"#F06C00","secondary":"#FFF3E8","accent":"#222222","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#FFF3E8","font_family":"Poppins (Modern)","logo_text":"SAINSBURY'S","logo_shape":"rect","badge_style":"nectar","category":"UK Grocery","compliance":"generic_uk","tagline":"Live well for less"},
    "ASDA": {"primary":"#78BE20","secondary":"#F5F5F5","accent":"#003087","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#E8F5D8","font_family":"Poppins (Modern)","logo_text":"ASDA","logo_shape":"pill","badge_style":"rollback","category":"UK Grocery","compliance":"generic_uk","tagline":"Save money. Live better."},
    "Morrisons": {"primary":"#FFCC00","secondary":"#003882","accent":"#FFFFFF","text_dark":"#003882","text_light":"#FFFFFF","bg_default":"#FFF9D6","font_family":"Poppins (Modern)","logo_text":"MORRISONS","logo_shape":"rect","badge_style":"more_card","category":"UK Grocery","compliance":"generic_uk","tagline":"More reasons to shop"},
    "Waitrose": {"primary":"#2E5234","secondary":"#F2F0EB","accent":"#C5A028","text_dark":"#1A2E1C","text_light":"#FFFFFF","bg_default":"#F2F0EB","font_family":"Lora (Elegant Serif)","logo_text":"WAITROSE","logo_shape":"rect","badge_style":"essential","category":"UK Grocery","compliance":"generic_uk","tagline":"Quality food, honestly priced"},
    "Marks & Spencer": {"primary":"#000000","secondary":"#F5F5F5","accent":"#B8960C","text_dark":"#000000","text_light":"#FFFFFF","bg_default":"#F5F5F5","font_family":"Lora (Elegant Serif)","logo_text":"M&S","logo_shape":"rect","badge_style":"sparks","category":"UK Grocery","compliance":"generic_uk","tagline":"This is not just food"},
    "Aldi": {"primary":"#0066CC","secondary":"#FF6600","accent":"#FFCC00","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#E6F0FF","font_family":"Poppins (Modern)","logo_text":"ALDI","logo_shape":"rect","badge_style":"specialbuy","category":"UK Grocery","compliance":"generic_uk","tagline":"Good different"},
    "Lidl": {"primary":"#0050AA","secondary":"#FFCC00","accent":"#E31B23","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#E6EEFF","font_family":"Poppins (Modern)","logo_text":"LIDL","logo_shape":"circle","badge_style":"weeklyoffer","category":"UK Grocery","compliance":"generic_uk","tagline":"Big on quality, Lidl on price"},
    "Co-op": {"primary":"#00B1A9","secondary":"#F5FFFE","accent":"#00514A","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#E6FAFA","font_family":"Poppins (Modern)","logo_text":"CO-OP","logo_shape":"pill","badge_style":"member_deal","category":"UK Grocery","compliance":"generic_uk","tagline":"Building a better world together"},
    "Iceland": {"primary":"#D01E25","secondary":"#FFFFFF","accent":"#003087","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#FFF0F0","font_family":"Poppins (Modern)","logo_text":"Iceland","logo_shape":"rect","badge_style":"bonus_card","category":"UK Grocery","compliance":"generic_uk","tagline":"That's why mums go to Iceland"},
    "Walmart": {"primary":"#0071CE","secondary":"#FFC220","accent":"#007DC6","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#E6F2FF","font_family":"Poppins (Modern)","logo_text":"WALMART","logo_shape":"pill","badge_style":"rollback","category":"US Retail","compliance":"us_generic","tagline":"Save money. Live better."},
    "Target": {"primary":"#CC0000","secondary":"#F5F5F5","accent":"#333333","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#FFF0F0","font_family":"Poppins (Modern)","logo_text":"Target","logo_shape":"circle","badge_style":"circle_deal","category":"US Retail","compliance":"us_generic","tagline":"Expect more. Pay less."},
    "Amazon": {"primary":"#FF9900","secondary":"#131921","accent":"#37475A","text_dark":"#111111","text_light":"#FFFFFF","bg_default":"#FAFAFA","font_family":"Poppins (Modern)","logo_text":"amazon","logo_shape":"pill","badge_style":"prime","category":"US Retail","compliance":"us_generic","tagline":"Find it. Love it. Buy it."},
    "Costco": {"primary":"#005DAA","secondary":"#E8314A","accent":"#FFFFFF","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#E6F0FF","font_family":"Poppins (Modern)","logo_text":"COSTCO","logo_shape":"rect","badge_style":"member_price","category":"US Retail","compliance":"us_generic","tagline":"The right products. The right price."},
    "Kroger": {"primary":"#004990","secondary":"#E31837","accent":"#FFFFFF","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#E6EEF8","font_family":"Poppins (Modern)","logo_text":"KROGER","logo_shape":"rect","badge_style":"generic","category":"US Retail","compliance":"us_generic","tagline":"Fresh for everyone"},
    "H&M": {"primary":"#E50010","secondary":"#FFFFFF","accent":"#222222","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#FFF5F5","font_family":"TeX Gyre Heros (Swiss)","logo_text":"H&M","logo_shape":"rect","badge_style":"sale_tag","category":"Fashion","compliance":"fashion","tagline":"Fashion and quality at the best price"},
    "Zara": {"primary":"#000000","secondary":"#FFFFFF","accent":"#888888","text_dark":"#000000","text_light":"#FFFFFF","bg_default":"#F8F8F8","font_family":"Lora (Elegant Serif)","logo_text":"ZARA","logo_shape":"rect","badge_style":"minimal_tag","category":"Fashion","compliance":"fashion","tagline":""},
    "Nike": {"primary":"#111111","secondary":"#FFFFFF","accent":"#FA5400","text_dark":"#111111","text_light":"#FFFFFF","bg_default":"#F5F5F5","font_family":"Poppins (Modern)","logo_text":"NIKE","logo_shape":"pill","badge_style":"generic","category":"Fashion","compliance":"fashion","tagline":"Just Do It"},
    "Adidas": {"primary":"#000000","secondary":"#FFFFFF","accent":"#1C7ED6","text_dark":"#000000","text_light":"#FFFFFF","bg_default":"#F0F0F0","font_family":"Poppins (Modern)","logo_text":"adidas","logo_shape":"rect","badge_style":"generic","category":"Fashion","compliance":"fashion","tagline":"Impossible is Nothing"},
    "ASOS": {"primary":"#2C2C2C","secondary":"#FF6687","accent":"#FF6687","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#FFF5F8","font_family":"Poppins (Modern)","logo_text":"ASOS","logo_shape":"rect","badge_style":"sale_tag","category":"Fashion","compliance":"fashion","tagline":"Fashion. Style. Individuality."},
    "Next": {"primary":"#000000","secondary":"#F5F5F5","accent":"#C41E3A","text_dark":"#111111","text_light":"#FFFFFF","bg_default":"#F5F5F5","font_family":"Liberation Sans (Clean)","logo_text":"NEXT","logo_shape":"rect","badge_style":"sale_tag","category":"Fashion","compliance":"generic_uk","tagline":"Style. Quality. Value."},
    "Primark": {"primary":"#0A2463","secondary":"#FFFFFF","accent":"#D62246","text_dark":"#111111","text_light":"#FFFFFF","bg_default":"#EEF2FF","font_family":"Poppins (Modern)","logo_text":"Primark","logo_shape":"rect","badge_style":"generic","category":"Fashion","compliance":"generic_uk","tagline":"Amazing Fashion. Amazing Prices."},
    "Barclays": {"primary":"#00AEEF","secondary":"#1F1F1F","accent":"#FFFFFF","text_dark":"#1F1F1F","text_light":"#FFFFFF","bg_default":"#E6F7FF","font_family":"Liberation Sans (Clean)","logo_text":"Barclays","logo_shape":"pill","badge_style":"finance","category":"Finance & Banking","compliance":"finance_uk","tagline":"It is what banking should be"},
    "HSBC": {"primary":"#DB0011","secondary":"#FFFFFF","accent":"#333333","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#FFF0F0","font_family":"Liberation Sans (Clean)","logo_text":"HSBC","logo_shape":"rect","badge_style":"finance","category":"Finance & Banking","compliance":"finance_uk","tagline":"Together we thrive"},
    "Lloyds Bank": {"primary":"#024731","secondary":"#009B77","accent":"#FFFFFF","text_dark":"#024731","text_light":"#FFFFFF","bg_default":"#E6F5EF","font_family":"Liberation Sans (Clean)","logo_text":"LLOYDS","logo_shape":"pill","badge_style":"finance","category":"Finance & Banking","compliance":"finance_uk","tagline":"By your side"},
    "NatWest": {"primary":"#42145F","secondary":"#FFFFFF","accent":"#DE0070","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#F5EDF8","font_family":"Poppins (Modern)","logo_text":"NatWest","logo_shape":"pill","badge_style":"finance","category":"Finance & Banking","compliance":"finance_uk","tagline":"We are what we do"},
    "Santander": {"primary":"#EC0000","secondary":"#FFFFFF","accent":"#333333","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#FFF0F0","font_family":"Liberation Sans (Clean)","logo_text":"Santander","logo_shape":"pill","badge_style":"finance","category":"Finance & Banking","compliance":"finance_uk","tagline":"Simple. Personal. Fair."},
    "Monzo": {"primary":"#FF5B5B","secondary":"#1A1A2E","accent":"#FFFFFF","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#FFF5F5","font_family":"Poppins (Modern)","logo_text":"monzo","logo_shape":"pill","badge_style":"fintech","category":"Finance & Banking","compliance":"finance_uk","tagline":"A bank account with superpowers"},
    "PayPal": {"primary":"#003087","secondary":"#009CDE","accent":"#012169","text_dark":"#003087","text_light":"#FFFFFF","bg_default":"#E6EEF8","font_family":"Poppins (Modern)","logo_text":"PayPal","logo_shape":"pill","badge_style":"fintech","category":"Finance & Banking","compliance":"us_generic","tagline":"The simpler, safer way to pay"},
    "NHS": {"primary":"#005EB8","secondary":"#FFFFFF","accent":"#003087","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#E6EEF8","font_family":"Liberation Sans (Clean)","logo_text":"NHS","logo_shape":"rect","badge_style":"health","category":"Healthcare","compliance":"healthcare_uk","tagline":"Your NHS. For you."},
    "Bupa": {"primary":"#C8102E","secondary":"#FFFFFF","accent":"#003057","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#FFF0F2","font_family":"Poppins (Modern)","logo_text":"BUPA","logo_shape":"rect","badge_style":"health","category":"Healthcare","compliance":"healthcare_uk","tagline":"Helping you find healthy"},
    "AXA Health": {"primary":"#00008F","secondary":"#FF1721","accent":"#FFFFFF","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#E6E6F8","font_family":"Liberation Sans (Clean)","logo_text":"AXA","logo_shape":"rect","badge_style":"health","category":"Healthcare","compliance":"healthcare_uk","tagline":"Know you can"},
    "Vitality": {"primary":"#E20074","secondary":"#FFFFFF","accent":"#4B0082","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#FFF0F8","font_family":"Poppins (Modern)","logo_text":"Vitality","logo_shape":"pill","badge_style":"health","category":"Healthcare","compliance":"healthcare_uk","tagline":"Making people healthier"},
    "Boots": {"primary":"#005EB8","secondary":"#FFFFFF","accent":"#E31B23","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#E6F0FF","font_family":"Poppins (Modern)","logo_text":"boots","logo_shape":"pill","badge_style":"advantage","category":"UK Pharmacy","compliance":"pharmacy_uk","tagline":"With you for life"},
    "Lloyds Pharmacy": {"primary":"#00A3E0","secondary":"#FFFFFF","accent":"#005082","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#E6F5FF","font_family":"Poppins (Modern)","logo_text":"LloydsPharmacy","logo_shape":"pill","badge_style":"health","category":"UK Pharmacy","compliance":"pharmacy_uk","tagline":"Caring for you"},
    "Superdrug": {"primary":"#E40C93","secondary":"#FFFFFF","accent":"#1A1A1A","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#FFF0FA","font_family":"Poppins (Modern)","logo_text":"Superdrug","logo_shape":"pill","badge_style":"health_beauty","category":"UK Pharmacy","compliance":"pharmacy_uk","tagline":"Feel good for less"},
    "Walgreens": {"primary":"#E31837","secondary":"#FFFFFF","accent":"#F5821F","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#FFF0F2","font_family":"Poppins (Modern)","logo_text":"walgreens","logo_shape":"pill","badge_style":"health","category":"US Pharmacy","compliance":"us_generic","tagline":"Trusted since 1901"},
    "CVS": {"primary":"#CC0000","secondary":"#FFFFFF","accent":"#1A1A1A","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#FFF0F0","font_family":"Liberation Sans (Clean)","logo_text":"CVS","logo_shape":"rect","badge_style":"health","category":"US Pharmacy","compliance":"us_generic","tagline":"Health is everything"},
    "Apple": {"primary":"#1D1D1F","secondary":"#F5F5F7","accent":"#0071E3","text_dark":"#1D1D1F","text_light":"#FFFFFF","bg_default":"#F5F5F7","font_family":"Liberation Sans (Clean)","logo_text":"Apple","logo_shape":"rect","badge_style":"minimal_tag","category":"Technology","compliance":"us_generic","tagline":"Think different"},
    "Samsung": {"primary":"#1428A0","secondary":"#FFFFFF","accent":"#1428A0","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#EEF0FF","font_family":"Poppins (Modern)","logo_text":"SAMSUNG","logo_shape":"rect","badge_style":"generic","category":"Technology","compliance":"us_generic","tagline":"Imagine the possibilities"},
    "Microsoft": {"primary":"#0078D4","secondary":"#FFFFFF","accent":"#107C10","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#E6F3FF","font_family":"Poppins (Modern)","logo_text":"Microsoft","logo_shape":"rect","badge_style":"generic","category":"Technology","compliance":"us_generic","tagline":"Empower every person"},
    "Currys": {"primary":"#6F2DA8","secondary":"#FFFFFF","accent":"#FF0000","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#F5EEFF","font_family":"Poppins (Modern)","logo_text":"currys","logo_shape":"pill","badge_style":"generic","category":"Technology","compliance":"generic_uk","tagline":"We start with you"},
    "Argos": {"primary":"#EE2022","secondary":"#FFFFFF","accent":"#333333","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#FFF0F0","font_family":"Poppins (Modern)","logo_text":"argos","logo_shape":"pill","badge_style":"generic","category":"Technology","compliance":"generic_uk","tagline":"Find it, get it, Argos it"},
    "McDonald's": {"primary":"#DA291C","secondary":"#FFC72C","accent":"#27251F","text_dark":"#27251F","text_light":"#FFFFFF","bg_default":"#FFF8E1","font_family":"Poppins (Modern)","logo_text":"McDonald's","logo_shape":"pill","badge_style":"generic","category":"Food & Beverage","compliance":"food_generic","tagline":"I'm lovin' it"},
    "Starbucks": {"primary":"#00704A","secondary":"#FFFFFF","accent":"#CBA258","text_dark":"#1E3932","text_light":"#FFFFFF","bg_default":"#E8F5EF","font_family":"Lora (Elegant Serif)","logo_text":"Starbucks","logo_shape":"circle","badge_style":"generic","category":"Food & Beverage","compliance":"us_generic","tagline":"To inspire and nurture the human spirit"},
    "Greggs": {"primary":"#003087","secondary":"#FFFFFF","accent":"#F8961C","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#E6EEF8","font_family":"Poppins (Modern)","logo_text":"GREGGS","logo_shape":"rect","badge_style":"generic","category":"Food & Beverage","compliance":"generic_uk","tagline":"Always fresh, always tasty"},
    "Costa Coffee": {"primary":"#5B0E20","secondary":"#FFFFFF","accent":"#C9972F","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#F8F0F0","font_family":"Lora (Elegant Serif)","logo_text":"Costa","logo_shape":"circle","badge_style":"generic","category":"Food & Beverage","compliance":"generic_uk","tagline":"Passionate about great coffee"},
    "Nando's": {"primary":"#B30000","secondary":"#FFFFFF","accent":"#E8920A","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#FFF0E6","font_family":"Poppins (Modern)","logo_text":"Nando's","logo_shape":"pill","badge_style":"generic","category":"Food & Beverage","compliance":"generic_uk","tagline":"Enjoy the journey"},
    "Ford": {"primary":"#003476","secondary":"#FFFFFF","accent":"#1A6EBD","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#E6EEF8","font_family":"Liberation Sans (Clean)","logo_text":"FORD","logo_shape":"pill","badge_style":"generic","category":"Automotive","compliance":"automotive","tagline":"Built Ford Tough"},
    "Volkswagen": {"primary":"#001E50","secondary":"#FFFFFF","accent":"#00B0F0","text_dark":"#001E50","text_light":"#FFFFFF","bg_default":"#E6EBF5","font_family":"Liberation Sans (Clean)","logo_text":"VW","logo_shape":"circle","badge_style":"generic","category":"Automotive","compliance":"automotive","tagline":"Das Auto"},
    "BMW": {"primary":"#1C69D4","secondary":"#000000","accent":"#FFFFFF","text_dark":"#000000","text_light":"#FFFFFF","bg_default":"#F0F4FB","font_family":"Lora (Elegant Serif)","logo_text":"BMW","logo_shape":"circle","badge_style":"minimal_tag","category":"Automotive","compliance":"automotive","tagline":"The Ultimate Driving Machine"},
    "British Airways": {"primary":"#002157","secondary":"#FFFFFF","accent":"#EB2226","text_dark":"#002157","text_light":"#FFFFFF","bg_default":"#EEF2F8","font_family":"Liberation Sans (Clean)","logo_text":"BA","logo_shape":"rect","badge_style":"generic","category":"Travel & Hospitality","compliance":"travel","tagline":"To fly. To serve."},
    "easyJet": {"primary":"#FF6600","secondary":"#FFFFFF","accent":"#1A1A1A","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#FFF5EE","font_family":"Poppins (Modern)","logo_text":"easyJet","logo_shape":"pill","badge_style":"generic","category":"Travel & Hospitality","compliance":"travel","tagline":"Make travel easy"},
    "Airbnb": {"primary":"#FF5A5F","secondary":"#FFFFFF","accent":"#00A699","text_dark":"#484848","text_light":"#FFFFFF","bg_default":"#FFF5F5","font_family":"Poppins (Modern)","logo_text":"airbnb","logo_shape":"pill","badge_style":"generic","category":"Travel & Hospitality","compliance":"us_generic","tagline":"Belong anywhere"},
    "Premier Inn": {"primary":"#7B2C9E","secondary":"#FFFFFF","accent":"#E8892B","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#F5EEF8","font_family":"Poppins (Modern)","logo_text":"Premier Inn","logo_shape":"rect","badge_style":"generic","category":"Travel & Hospitality","compliance":"generic_uk","tagline":"Everything's Premier but the price"},
    "L'Oréal": {"primary":"#AA0000","secondary":"#FFFFFF","accent":"#C9972F","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#FFF8F0","font_family":"Lora (Elegant Serif)","logo_text":"L'ORÉAL","logo_shape":"rect","badge_style":"generic","category":"Beauty & Personal Care","compliance":"beauty","tagline":"Because you're worth it"},
    "Dove": {"primary":"#E8C99A","secondary":"#FFFFFF","accent":"#5B4E3E","text_dark":"#2C1F0E","text_light":"#FFFFFF","bg_default":"#FDF6EE","font_family":"Lora (Elegant Serif)","logo_text":"dove","logo_shape":"pill","badge_style":"generic","category":"Beauty & Personal Care","compliance":"beauty","tagline":"Real beauty is universal"},
    "Nivea": {"primary":"#003189","secondary":"#FFFFFF","accent":"#7BA7BC","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#EEF2FF","font_family":"Liberation Sans (Clean)","logo_text":"NIVEA","logo_shape":"circle","badge_style":"generic","category":"Beauty & Personal Care","compliance":"beauty","tagline":"Feel closer"},
    "Aviva": {"primary":"#4B0082","secondary":"#FFFFFF","accent":"#FF8C00","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#F5EEF8","font_family":"Poppins (Modern)","logo_text":"Aviva","logo_shape":"pill","badge_style":"finance","category":"Insurance","compliance":"finance_uk","tagline":"With you today, for a better tomorrow"},
    "Admiral": {"primary":"#AE1C28","secondary":"#FFFFFF","accent":"#003087","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#FFF0F0","font_family":"Poppins (Modern)","logo_text":"Admiral","logo_shape":"pill","badge_style":"finance","category":"Insurance","compliance":"finance_uk","tagline":"We're with you all the way"},
    "British Gas": {"primary":"#0097CE","secondary":"#FFFFFF","accent":"#003C6C","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#E6F5FF","font_family":"Poppins (Modern)","logo_text":"British Gas","logo_shape":"rect","badge_style":"generic","category":"Energy & Utilities","compliance":"generic_uk","tagline":"Take care of what matters"},
    "Octopus Energy": {"primary":"#EF4082","secondary":"#FFFFFF","accent":"#6A4C93","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#FFF0F5","font_family":"Poppins (Modern)","logo_text":"Octopus","logo_shape":"pill","badge_style":"generic","category":"Energy & Utilities","compliance":"generic_uk","tagline":"Energy that's good for the planet"},
    "Vodafone": {"primary":"#E60000","secondary":"#FFFFFF","accent":"#333333","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#FFF0F0","font_family":"Poppins (Modern)","logo_text":"Vodafone","logo_shape":"circle","badge_style":"generic","category":"Telecom","compliance":"generic_uk","tagline":"The future is exciting"},
    "EE": {"primary":"#00B0CA","secondary":"#FFFFFF","accent":"#000000","text_dark":"#1A1A1A","text_light":"#FFFFFF","bg_default":"#E6F8FA","font_family":"Poppins (Modern)","logo_text":"EE","logo_shape":"rect","badge_style":"generic","category":"Telecom","compliance":"generic_uk","tagline":"Powerful connection"},
    "Custom Brand": {"primary":"#333333","secondary":"#F5F5F5","accent":"#666666","text_dark":"#111111","text_light":"#FFFFFF","bg_default":"#F5F5F5","font_family":"Poppins (Modern)","logo_text":"BRAND","logo_shape":"pill","badge_style":"generic","category":"Custom","compliance":"none","tagline":""},
}

BRAND_CATEGORIES = {
    "UK Grocery":            ["Tesco","Sainsbury's","ASDA","Morrisons","Waitrose","Marks & Spencer","Aldi","Lidl","Co-op","Iceland"],
    "US Retail":             ["Walmart","Target","Amazon","Costco","Kroger"],
    "Fashion":               ["H&M","Zara","Nike","Adidas","ASOS","Next","Primark"],
    "Finance & Banking":     ["Barclays","HSBC","Lloyds Bank","NatWest","Santander","Monzo","PayPal"],
    "Healthcare":            ["NHS","Bupa","AXA Health","Vitality"],
    "UK Pharmacy":           ["Boots","Lloyds Pharmacy","Superdrug"],
    "US Pharmacy":           ["Walgreens","CVS"],
    "Technology":            ["Apple","Samsung","Microsoft","Currys","Argos"],
    "Food & Beverage":       ["McDonald's","Starbucks","Greggs","Costa Coffee","Nando's"],
    "Automotive":            ["Ford","Volkswagen","BMW"],
    "Travel & Hospitality":  ["British Airways","easyJet","Airbnb","Premier Inn"],
    "Beauty & Personal Care":["L'Oréal","Dove","Nivea"],
    "Insurance":             ["Aviva","Admiral"],
    "Energy & Utilities":    ["British Gas","Octopus Energy"],
    "Telecom":               ["Vodafone","EE"],
    "Custom":                ["Custom Brand"],
}

FONT_MAP = {
    "Poppins (Modern)": {
        "regular": "/usr/share/fonts/truetype/google-fonts/Poppins-Regular.ttf",
        "bold":    "/usr/share/fonts/truetype/google-fonts/Poppins-Bold.ttf",
        "medium":  "/usr/share/fonts/truetype/google-fonts/Poppins-Medium.ttf",
    },
    "Liberation Sans (Clean)": {
        "regular": "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
        "bold":    "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
        "medium":  "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
    },
    "DejaVu Sans (Neutral)": {
        "regular": "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        "bold":    "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
        "medium":  "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
    },
    "Lora (Elegant Serif)": {
        "regular": "/usr/share/fonts/truetype/google-fonts/Lora-Variable.ttf",
        "bold":    "/usr/share/fonts/truetype/google-fonts/Lora-Variable.ttf",
        "medium":  "/usr/share/fonts/truetype/google-fonts/Lora-Variable.ttf",
    },
    "FreeSans (Rounded)": {
        "regular": "/usr/share/fonts/truetype/freefont/FreeSans.ttf",
        "bold":    "/usr/share/fonts/truetype/freefont/FreeSansBold.ttf",
        "medium":  "/usr/share/fonts/truetype/freefont/FreeSansBold.ttf",
    },
    "FreeSerif (Classic)": {
        "regular": "/usr/share/fonts/truetype/freefont/FreeSerif.ttf",
        "bold":    "/usr/share/fonts/truetype/freefont/FreeSerifBold.ttf",
        "medium":  "/usr/share/fonts/truetype/freefont/FreeSerifBold.ttf",
    },
    "TeX Gyre Heros (Swiss)": {
        "regular": "/usr/share/texmf/fonts/opentype/public/tex-gyre/texgyreheros-regular.otf",
        "bold":    "/usr/share/texmf/fonts/opentype/public/tex-gyre/texgyreheros-bold.otf",
        "medium":  "/usr/share/texmf/fonts/opentype/public/tex-gyre/texgyreheros-bold.otf",
    },
}

LAYOUT_PRESETS = {
    "Product Hero":     {"packshot_side":"right", "text_side":"left",   "text_align":"left",   "overlay":"band"},
    "Centered Minimal": {"packshot_side":"center","text_side":"bottom",  "text_align":"center", "overlay":"gradient"},
    "Bold Left":        {"packshot_side":"left",  "text_side":"right",  "text_align":"left",   "overlay":"solid"},
    "Full Bleed":       {"packshot_side":"full",  "text_side":"bottom",  "text_align":"left",   "overlay":"frosted"},
    "Split Panel":      {"packshot_side":"right", "text_side":"left",   "text_align":"left",   "overlay":"split"},
    "Top Banner":       {"packshot_side":"bottom","text_side":"top",    "text_align":"center", "overlay":"band"},
    "Diagonal Cut":     {"packshot_side":"right", "text_side":"left",   "text_align":"left",   "overlay":"diagonal"},
}

BG_PATTERNS = {
    "None":          "none",
    "Subtle Dots":   "subtle_dots",
    "Diagonal Lines":"diagonal_lines",
    "Corner Circles":"corner_circles",
    "Geometric":     "geometric_slab",
    "Soft Noise":    "soft_noise",
    "Wave Lines":    "wave_lines",
    "Crosshatch":    "crosshatch",
    "Halftone":      "halftone",
    "Grid":          "grid",
}

BG_GRADIENTS = {
    "Brand Default": None,
    "Warm Cream":    ("#FFF8EE","#F0E0C8"),
    "Cool Blue":     ("#E8F4FD","#C8DFF5"),
    "Fresh Mint":    ("#E8F5F0","#C8EAD8"),
    "Deep Navy":     ("#1A2A4A","#0D1A2E"),
    "Soft Rose":     ("#FDF0F0","#F5D5D5"),
    "Pure White":    ("#FFFFFF","#F0F0F0"),
    "Charcoal":      ("#3A3A3A","#1A1A1A"),
    "Sunset":        ("#FFF0D8","#FFD0A0"),
    "Lavender":      ("#F0EAF8","#DDD0F0"),
    "Forest":        ("#E8F5E8","#C8E8C8"),
    "Ocean":         ("#E0F4FF","#B0D8F5"),
    "Gold":          ("#FFF8E0","#F0D090"),
    "Midnight":      ("#0D0D1A","#1A1A35"),
    "Blush":         ("#FFF0F5","#FFD0E0"),
}

COLOR_PALETTES = {
    "Professional":  ["#002858","#00539F","#BFE0F5","#FFFFFF","#E31837"],
    "Warm Neutral":  ["#3D2B1F","#8B5E3C","#D4A574","#F5E6D3","#FFFFFF"],
    "Fresh Green":   ["#1A3A1A","#2E5234","#78BE20","#E8F5D8","#FFFFFF"],
    "Bold Vibrant":  ["#CC0000","#FF6600","#FFCC00","#FFFFFF","#111111"],
    "Elegant Dark":  ["#000000","#1A1A1A","#333333","#888888","#FFFFFF"],
    "Pastel Soft":   ["#FFB3C6","#FFC8A2","#D4F0C0","#B8D8F8","#E8B4FF"],
    "Corporate":     ["#003087","#0066CC","#99BBDD","#E6EEFF","#FFFFFF"],
    "Luxury Gold":   ["#1A0A00","#4A2800","#C9972F","#F0D898","#FFFFFF"],
    "Tech Modern":   ["#0D1117","#161B22","#1C69D4","#58A6FF","#FFFFFF"],
    "Health & Care": ["#005EB8","#41B6E6","#E8F4FC","#FFFFFF","#003087"],
    "Finance":       ["#003087","#004B87","#C9972F","#F5F0E8","#FFFFFF"],
    "Eco":           ["#1B5E20","#2E7D32","#81C784","#E8F5E9","#FFFFFF"],
}
